### PR TITLE
Unknown tag support in comment grammar

### PR DESCRIPTION
**Pull request by alexstrat**
When hitting an unknown tag the comment parser currently fails.

This commit adds unknown tags support at grammar level at least.. Should something be done with transform rules ?

### CODE REVIEW

**Comment by jdeal** [comment]
I agree it's too limited the way it is. For my purposes, I have to have doctor fail if it hits a tag it doesn't know (because our docs are then known to be wrong). So, this would at least have to be an option to allow unknown tags or not.

If you add an option to lib/cli.js, disabled by default, I'll take that. Not sure what a good option name would be, but if you do something verbose, like allow-unknown-tags, I can always add a shorter alias later.

It would also be nice if the tags didn't have to be eaten as in your change. Unfortunately, there's no universal grammar for JSDoc tags. They all have their own unique syntax. But unknown tags could at least be treated like description tags, where they just take the text to the next tag and dump that in a description. The grammar could return a tag with the name set to whatever the tag name is, and the value as the text. The default transform (transform/default.js) could then have an "unknown" key in commentTagFunctions, and that could be called for any unknown tags.

It would be nice if it were easier to add custom tags. I'm not going to think about how that would work right now.

**Comment by alexstrat** [comment]
Yes, we don't seek the same purpose: on my side, I expected doctor to go its way on unknown tag. Let's try with an option as you say..

I think it's not feasible to add an option to the grammar itself to make it fail or not. I think that we should let the grammar handle the unknown tag and let the layers above decide what to do with it, based on options. 

For instance, the transform layer would add to ast node the unknown tags in an dedicated array (or whatever) thanks to an `"unknown"` key in _commentTagFunctions_. And then, a report rules would throw an expressive error ("tag caribou unknown") if any unknown tag is found. This throw can be disabled based on an option.

While I think I can esasily add the `"unknown"` key, i'm in opposite not yet very familiar with the rules system, so, my question is: is there currently any way to - programmatically - pass options to (default) report rules ?

Moreover,

> It would also be nice if the tags didn't have to be eaten as in your change. [...] unknown tags could at least be treated like description tags.

I don't get what you mean here. The given support of unknowns tags acts exactly like that.. `@caribou hello desc` produces (see tests):

``` js
tag.name === 'caribou';
tag.value.description === 'hello desc';
```

You'd prefer : `tag.value === 'hello desc'` ?

**Comment by jdeal** [comment]
Sorry, yeah, I see your grammar isn't eating it. (Dealing with a cold; head is kind of foggy right now.) It's just that transform/default.js isn't doing anything with it, so it is effectively eaten. The format you have is fine and would allow for other info to go into the value, such as unknown = true or whatever.

I think it would be possible to do the conditional work in the grammar, but it might be a little strange. I think in the setup code in the grammar, you could require in doctor and ask for its current options. That makes it reliant on global options though, which I like to avoid. The parser is synchronous though, so it should be entirely safe. It would obviously be better if the options could be passed in, but I don't think PEG.js allows that.

What you describe is probably better anyway, as it leaves the grammar as dumb and declarative as possible, which is preferred. I don't think the report has to be the one to throw the error though. I think the transform can throw an error as soon as it hits an unknown tag (if the option isn't set to allow unknowns). Rules are synchronous, so throws should be fine. I just don't know how well I'm handling the bubbling right now.

**Comment by alexstrat** [comment]
OK fine. Eventually, I think it's better to throw something (or not) in one of the transform rules.. I'll give a try soon. And how could I write test for this feature ?

**Comment by alexstrat** [comment]
Thx Travis.. :/

So the throw is implemented as I said, and seems to work as expected..

However, seems that the `options` variable passed in [doctor.examine](https://github.com/jdeal/doctor/blob/master/lib/doctor.js#L304) is overridden somewhere before calling [transform](https://github.com/jdeal/doctor/blob/master/lib/doctor.js#L57), making any `allowUnknownTags` option disappear.. Weird, isn't it ?

**Comment by jdeal** [comment]
When you call doctor.examine, it in turn calls findRequired, which then does another doctor.examine, just to find any required files. I'm not implicitly passing all options through to that, so maybe that's what you're seeing?

**Comment by jdeal** [comment]
Unless I'm missing it, I'm not seeing an option in cli.js. I can add it easy enough; just making sure we're on the same page.

**Comment by alexstrat** [comment]
I am trying here to add to the _programmatic API_ (aka [doctor.examine](https://github.com/jdeal/doctor/blob/master/lib/doctor.js#L307)) an option (`allowUnknownTags`) that should propagate to the options passed in transform rules (thru [transform](https://github.com/jdeal/doctor/blob/master/lib/doctor.js#L57)). 

However I don't manage to do it, surely since, as you say, not all options are passed thru `findRequired`. But I don't get how to _recover_ the lost option. Could you help me ?

Once this done, adding an option to the cli is not difficult (since the cli uses the programmatic API)..

**Comment by jdeal** [comment]
I went ahead and made this the default. I changed allowUnknownTags to just unknown. So you just set it to false when you don't want to allow unknown tags. (or ---no-unknown on the command-line)

Also, #17 fixes the pass through. All options that aren't explicitly overridden by findRequired will be passed through to examine.

**Comment by alexstrat** [comment]
Okay, good ! Thanks !

**Pull request merged**
